version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
#env:
#  variables:
#    "version" : "0.2"
#  exportedVariables:
#    - version

steps:
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 1300
    command: |
      mvn clean install
  - type: Command
    name: "make Jar"
    timeoutInSeconds: 1300
    command: |
      cd ${OCI_WORKSPACE_DIR}/helidon-movie-api-mp/target
      jar -cvf helidon-movie-api-mp-all.jar helidon-movie-api-mp.jar
outputArtifacts:
  - name: OUTPUT
    type: BINARY
    location: ${OCI_WORKSPACE_DIR}/helidon-movie-api-mp/target/helidon-movie-api-mp-all.jar
